### ISSUE TITLE
Establish a TOM based on TOM Toolkit

### ISSUE THREAD

**Issue by manning-ncsa** [scimma/alert-integration-demo#3]
Create a new TOM based on TOM Toolkit and deploy it. Implement authentication via our existing Keycloak server.

**Comment by anaqreon** [comment]
The demo TOM is online at https://antares.ncsa.illinois.edu/tom/. OIDC authentication is provided by our Antares Keycloak server and CILogon.

**Comment by manning-ncsa** [comment]
The demo TOM is online at https://antares.ncsa.illinois.edu/tom/. OIDC authentication is provided by our Antares Keycloak server and CILogon.
